
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$git_commit\
$hostname\
$fill\
$nodejs\
$rust\
$c\
$python\
$golang\
$haskell\
$elixir\
${custom.hledger} $cmd_duration $jobs $time\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "blue"
read_only= "🔒"

[time]
format = "[$time]($style)"
disabled = false
style = "purple"

[nodejs]
format = "[$symbol($version )]($style)"

[elixir]
symbol = "🔮 "

[rust]
format = "[$symbol($version )]($style)"

[c]
detect_extensions = ["c", "h", "cc", "cpp", "hh", "hpp"]

[custom.hledger]
detect_extensions= ['journal', 'ledger']
symbol = "💸"
style = "green"
format = "[$symbol](style)"
